ae_booking_homepage:
    path:     /
    defaults: { _controller: AEBookingBundle:Customer:index }



ae_booking_slots:
    path:     /slots
    defaults: { _controller: AEBookingBundle:Customer:getSlots}
