services:

  ae_booking.quota.quota_customer:
    class: AE\BookingBundle\Quota\QuotaCustomer
    arguments: ['%max_slot%','@doctrine.orm.entity_manager']

  ae_booking.quota.quota_holiday:
    class: AE\BookingBundle\Quota\QuotaHoliday
    arguments: ['%max_slot%', '@doctrine.orm.entity_manager']