################### USER #######################################
ae_backoffice_user_index:
    path:     /utilisateurs/photographes
    defaults: { _controller: AEBackOfficeBundle:User:index }

ae_backoffice_user_add:
    path:     /utilisateurs/ajouter
    defaults: { _controller: AEBackOfficeBundle:User:add }

ae_backoffice_user_edit:
    path:     utilisateurs/editer/{id}
    defaults: { _controller: AEBackOfficeBundle:User:edit }
    requirements:
      id: \d+

ae_backoffice_user_delete:
    path:     utilisateurs/supprimer
    defaults: { _controller: AEBackOfficeBundle:User:delete }


################### Holiday #################################
ae_backoffice_holiday_index:
    path:     /holidays/{userId}
    defaults: { _controller: AEBackOfficeBundle:Holiday:index }
    requirements:
      userId: \d+

ae_backoffice_holiday_add:
    path:     /holidays/add
    defaults: { _controller: AEBackOfficeBundle:Holiday:add }

ae_backoffice_holiday_edit:
    path:     /holidays/edit/{id}
    defaults: { _controller: AEBackOfficeBundle:Holiday:edit }
    requirements:
      userId: \d+

ae_backoffice_holiday_delete:
    path:     /holidays/delete/{id}
    defaults: { _controller: AEBackOfficeBundle:Holiday:delete }
    requirements:
      userId: \d+

ae_backoffice_grid:
    path: /holidays/grid
    defaults: { _controller: AEBackOfficeBundle:Holiday:grid }


