################### CUSTOMER #######################################
ae_backoffice_customer_index:
    path:     /reservations
    defaults: { _controller: AEBackOfficeBundle:Customer:index }

ae_backoffice_customer_date:
    path:     /reservations/filtre/{date}
    defaults: { _controller: AEBackOfficeBundle:Customer:date}
    requirements:
      date:  "[0-9]{4}-[0-9]{2}-[0-9]{2}"

ae_backoffice_customer_view:
    path:     reservations/detail/{id}
    defaults: { _controller: AEBackOfficeBundle:Customer:view }
    requirements:
          id: \d+

ae_backoffice_customer_edit:
    path:     reservations/editer/{id}
    defaults: { _controller: AEBackOfficeBundle:Customer:edit }
    requirements:
          id: \d+

ae_backoffice_customer_delete:
    path:     reservations/supprimer/{id}
    defaults: { _controller: AEBackOfficeBundle:Customer:delete }
    requirements:
          id: \d+

ae_backoffice_customer_calendar:
    path:     reservations/calendrier
    defaults: { _controller: AEBackOfficeBundle:Customer:calendar }

ae_backoffice_customer_ajax:
    path:     /reservations/ajax
    defaults: { _controller: AEBackOfficeBundle:Customer:ajaxCalendarEvents }

################### MATERNITY #######################################
ae_backoffice_maternity_index:
    path:     /maternites
    defaults: { _controller: AEBackOfficeBundle:Maternity:index }

ae_backoffice_maternity_add:
    path:     /maternites/ajouter
    defaults: { _controller: AEBackOfficeBundle:Maternity:add }

ae_backoffice_maternity_edit:
    path:     maternites/editer/{id}
    defaults: { _controller: AEBackOfficeBundle:Maternity:edit }
    requirements:
          id: \d+

ae_backoffice_maternity_delete:
    path:     maternites/supprimer/{id}
    defaults: { _controller: AEBackOfficeBundle:Maternity:delete }
    requirements:
          id: \d+

################### USER #######################################
ae_backoffice_user_index:
    path:     /utilisateurs/photographes
    defaults: { _controller: AEBackOfficeBundle:User:index }

ae_backoffice_user_add:
    path:     /utilisateurs/ajouter
    defaults: { _controller: AEBackOfficeBundle:User:add }

ae_backoffice_user_edit:
    path:     utilisateurs/editer/{id}
    defaults: { _controller: AEBackOfficeBundle:User:edit }
    requirements:
      id: \d+

ae_backoffice_user_delete:
    path:     utilisateurs/supprimer/{id}
    defaults: { _controller: AEBackOfficeBundle:User:delete }
    requirements:
          id: \d+


################### Holiday #################################
ae_backoffice_holiday_index:
    path:     /conges
    defaults: { _controller: AEBackOfficeBundle:Holiday:index }


ae_backoffice_holiday_view:
    path:     /conges/gerer/{userId}
    defaults: { _controller: AEBackOfficeBundle:Holiday:view }
    requirements:
      userId: \d+

ae_backoffice_holiday_add:
    path:     /conges/ajouter/{userId}
    defaults: { _controller: AEBackOfficeBundle:Holiday:add }
    requirements:
        userId: \d+

ae_backoffice_holiday_ajax:
    path:     /conges/ajax/{userId}
    defaults: { _controller: AEBackOfficeBundle:Holiday:getAjaxHolidays }
    requirements:
        userId: \d+

ae_backoffice_holiday_delete:
    path:     /holidays/delete/{id}
    defaults: { _controller: AEBackOfficeBundle:Holiday:delete }
    requirements:
      userId: \d+


