<?php

namespace AE\BookingBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MaternityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaternityRepository extends EntityRepository
{

    public function getActiveMaternity(){
        $qb = $this->createQueryBuilder('m');

        $qb
            ->where('m.isActive = :active')->setParameter('active', true)
            ->orderBy('m.name', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
