<?php

namespace AE\BookingBundle\Repository;

/**
 * MaternityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaternityRepository extends \Doctrine\ORM\EntityRepository
{
}
