<?php

namespace AE\BookingBundle\Repository;

/**
 * QuotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotaRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSlots()
    {
        $qb = $this->createQueryBuilder('q');

        $qb
            ->where('q.quotaNb <= :nb')->setParameter('nb', 0)
            ->andWhere('q.quotaDay >= :today')->setParameter('today', new \DateTime())
            ->orderBy('q.quotaNb', 'ASC');

        return $qb->getQuery()->getResult();
    }


    public function getHolidaySlots( $startDate, $endDate )
    {
        $qb = $this->createQueryBuilder('q')
            ->where('q.quotaDay >= :startDate' )->setParameter('startDate', $startDate )
            ->andWhere('q.quotaDay <= :endDate')->setParameter('endDate', $endDate)
            ->orderBy('q.quotaDay', 'ASC');

        return $qb->getQuery()->getResult();
    }


}
