<?php

namespace AE\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdmins()
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->select('COUNT(u)')
            ->where('u.roles LIKE :role')->setParameter('role', "%ROLE_ADMIN%");

        return $qb->getQuery()->getSingleScalarResult();
    }
}
